# Freebox service entries description.

reboot:

flip:
  name: Flip camera
  description: Flips the camera image vertically.
  target:
    entity:
      domain: camera

remote:
  name: Send command
  description: Sends a command to the Freebox Player.
  target:
    entity:
      domain: remote
  fields:
    code:
      name: Command code
      description: The command code to send to the Freebox Player.
      example: "power"
      required: true
      selector:
        select:
          options:
            - "red"
            - "green"
            - "blue"
            - "yellow"
            - "power"
            - "list"
            - "tv"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "back"
            - "0"
            - "swap"
            - "info"
            - "epg"
            - "mail"
            - "media"
            - "help"
            - "options"
            - "pip"
            - "vol_inc"
            - "vol_dec"
            - "ok"
            - "up"
            - "right"
            - "down"
            - "left"
            - "prgm_inc"
            - "prgm_dec"
            - "mute"
            - "home"
            - "rec"
            - "bwd"
            - "prev"
            - "play"
            - "fwd"
            - "next"
    long_press:
      name: Long press
      description: If true, the command is sent as a long press.
      default: false
      selector:
        boolean:
    repeat:
      name: Repeat count
      description: Number of times to repeat the command (0 for no repeat).
      default: 0
      selector:
        number:
          min: 0
          max: 10
          step: 1
